kind: pipeline
type: docker
name: default

steps:
  - name: web-ui
    image: node
    commands:
      - cd web-ui
      - yarn install --silent
      - yarn lint
      - yarn test --ci
    when:
      event:
        - pull_request

  - name: server
    image: rust
    commands:
      - rustup component add clippy
      - cargo clippy --quiet --locked --all-features -- -D warnings
      - cargo test --quiet --locked
    when:
      event:
        - pull_request
