kind: pipeline
type: docker
name: default

steps:
  - name: web-ui
    image: node
    commands:
      - cd web-ui
      - yarn install
      - yarn lint
      - yarn test
    when:
      event:
        - pull_request

  - name: server
    image: rust
    commands:
      - rustup component add clippy
      - cd server
      - cargo clippy --all-features -- -D warnings
      - cargo test
    when:
      event:
        - pull_request
