[package]
name = "sprokit_maze"
version = "0.1.0"
authors = ["Michael Daffin <michael@daffin.io>"]
edition = "2018"

[dependencies]
derive_more = "0.15.0"
rand = "0.7.2"
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
serde_json = "1.0.41"
lazy_static = "1.4.0"
