#!/usr/bin/env bash
set -eou pipefail

: "${MAZE_SERVER_URL?}"

maze_server_urls() {
    IFS=',' read -ra URLS <<< "${MAZE_SERVER_URL}"
    for url in "${URLS[@]}"; do
        [[ -z "$url" ]] || echo "    server $url;"
    done
}

cat <<EOF >/etc/nginx/conf.d/default.conf
upstream maze_servers {
$(maze_server_urls)
}

server {
    listen       80;
    server_name  localhost;
    access_log  /dev/stdout  main;

    location / {
        root   /usr/share/nginx/html;
        index  index.html;
    }

    location /api/game/maze/ {
        proxy_set_header HOST \$host;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;

        proxy_pass http://maze_servers/;
    }
}
EOF

nginx -g "daemon off;"
